name: TrustWalletCore
options:
  bundleIdPrefix: com.trustwallet
  createIntermediateGroups: true
settings:
  base:
    BUILD_LIBRARY_FOR_DISTRIBUTION: true
    CLANG_CXX_LANGUAGE_STANDARD: c++17
    CODE_SIGN_STYLE: Manual
    ENABLE_BITCODE: false
    LIBRARY_SEARCH_PATHS: wallet-core/build/ios
    SUPPORTS_MACCATALYST: false
    SWIFT_VERSION: 5.0
  configs:
    release:
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
targets:
  WalletCore:
    dependencies:
    - carthage: SwiftProtobuf
    - framework: libprotobuf.a
    - framework: libTrezorCrypto.a
    - framework: libCore.a
    - sdk: libc++.tbd
    deploymentTarget:
      iOS: '12.0'
    platform:
    - iOS
    settings:
      CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION: YES_ERROR
      SKIP_INSTALL: false
    sources:
    - headerVisibility: public
      path: wallet-core/include
    - wallet-core/swift/Sources
    - TrustWalletCore
    type: framework
